apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-{{ .Values.pvcName }}
  namespace: {{ .Values.jenkinsNamespace }}
spec:
  storageClassName: local-{{ .Values.className }}
  accessModes:
    - {{ .Values.localPvcAccessMode }}
  resources:
    requests:
      storage: {{ .Values.localPvcSize }}
