apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-{{ .Values.className }}
provisioner: {{ .Values.classLocalProvisioner }}
volumeBindingMode: {{ .Values.classVolumeBindingMode }}
