apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-volv-pvc
  namespace: jenkins
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: jenkins-longhorn
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonar-volv-pvc
  namespace: jenkins
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: sonar-longhorn
  resources:
    requests:
      storage: 20Gi
