apiVersion: v1
kind: PersistentVolume
metadata:
  name: repo-prod
  labels:
    type: local
spec:
  storageClassName: local-storage-prod
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/repositorio"
